language: go
sudo: false
go:
  - 1.4.2
  - 1.5
  - 1.6
  - tip
install:
  - make install
before_script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - make travis
notifications:
  email: false
